### ISSUE TITLE
marshal and unmarshal 'SortedSet' struct

### ISSUE THREAD

**Issue by mdaliyan** [wangjia184/sortedset#1]
Hi
Is't there a way to marshal and unmarshal `SortedSet` struct?
I need to store it in cache as byte

**Comment by jyzhou17** [comment]
hey，is there any way to specify sorting in ascending or descending order?

**Comment by wangjia184** [comment]
No,  you may extend it

**Comment by mdaliyan** [comment]
Too late, I used another solution. Thanks
